Add Katello 4.7.5 to config releases and fix some 4.7 releases
theforeman/tool_belt pull request #531
Opened 2023-04-19 18:27 UTC by ianballou

I noticed that 4.7 had its own releases in the prior releases section, so I fixed it.

2023-04-25 20:01 UTC, chris1984 approved these changes

2023-04-25 20:01 UTC, chris1984 commented
@zjhuntin can this get a merge?

2023-04-27 16:10 UTC, chris1984 requested changes
@ianballou Can you add the 4.7.4 to the prior releases section?

2023-04-27 17:50 UTC, ianballou commented
> @ianballou Can you add the 4.7.4 to the prior releases section?

Does 4.7.4 need to be in the prior releases part if it's already in the releases section? I updated it, but it's kinda weird that tool belt wouldn't also search the releases section for other cherry picks.

2023-05-02 15:09 UTC, chris1984 commented
Ignore my comment, if you don't mind reverting my comment. looking at the other configs those 4.7.x need to be in the releases and 4.6 would be in the prior spot

2023-05-02 18:51 UTC, chris1984 approved these changes
ACK, @ekohl can this get a merge?

2023-05-02 20:04 UTC, merged